### ISSUE TITLE
Arduino zero 

### ISSUE THREAD

**Issue by carramar** [MHeironimus/ArduinoJoystickLibrary#296] opened 2024-10-12 07:00 UTC
Arduino zero has been the most powerful native usb arduino for almost a decade and somehow this library still doesnt support it. it claims it does but it doesnt.

**Comment by per1234** [comment] 2024-10-12 12:10
Duplicate of:

- https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/51
- https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/99
- https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/283
- And your own https://github.com/MHeironimus/ArduinoJoystickLibrary/issues/295

@carramar please close your duplicate issues to avoid cluttering up the issue tracker.

**Comment by MHeironimus** [comment] 2024-10-14 03:43
Closing as this is a duplicate of the issues listed in prior comments.

**Closed as completed by MHeironimus** 2024-10-14 03:43 UTC
Labels: duplicate
